---
title: "Workflow validation"
author: "Molecular Diagnostic Unit -- University Hospital Basel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  diroi: ''
editor_options: 
  chunk_output_type: console
---

```{r comparisons, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(magrittr)
diroi = params$diroi
```


```{r function, include=FALSE}
## FUNCTIONS
extract_parameters_from_dirname = function(watchdog_dirpath){
  mod_path = gsub("-",'_',watchdog_dirpath)
  rec = stringr::str_split(mod_path, pattern ="_", simplify = FALSE)[[1]]
  rec = rec[1:4]
  parameters = data.frame(name = watchdog_dirpath,
                            pcr_id = rec[1],
                            Bno = rec[2],
                          panel = rec[3],
                          wf_version = rec[4])
  return(parameters)
}
dload_DT = function(data_table){
  data_table %>%
  DT::datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(25,50,-1),
                                             c(25,50,"All"))))
}
extract_chr = function(locusstring){
  chr = stringr::str_extract(locusstring, pattern = 'chr.+?(?=:)')
  return(chr)
}
 
extract_start = function(locusstring){
  start = stringr::str_extract(locusstring, pattern = '(?<=chr.{1,2}:)\\d+')
  start = as.numeric(start)
return(start)
}

return_discordant_coordinates = function(input_file, subset_table){
  toi = subset(input_file, uid %in% subset_table$uid)
  toi = dplyr::select(toi, locus, filepath)
  toi$chr = extract_chr(toi$locus)
  toi$start = extract_start(toi$locus)
  toi$end = extract_start(toi$locus)
  toi = dplyr::relocate(toi, chr, start, end)
  toi = dplyr::select(toi, -locus)
  return(toi)
}
join_parameters_and_res = function(results_table){
  results_table = dplyr::filter(results_table, !is.na(value))
  parameters = dplyr::bind_rows(lapply(results_table$name,extract_parameters_from_dirname))
  joined_table = dplyr::left_join(results_table, parameters) 
  joined_table = dplyr::distinct(joined_table)
  return(joined_table)
}
count_variant_wf_version = function(parameter_table){
  parameter_table = dplyr::select(parameter_table,-name,-locus) %>%
  dplyr::group_by(chr, start, end,gene,coding,amino_acid_change,wf_version) %>%
  dplyr::count(sort = TRUE) %>%
  tidyr::pivot_wider(names_from = wf_version,
                     values_from = n)
  return(parameter_table)
}

remove_na_entries = function(res_list){
  res_table = dplyr::bind_rows(res_list[!is.na(res_list)])
  return(res_table)
}

add_coordinates = function(res_table){
  res_table = tidyr::separate(res_table, col = 'uid', into = c('gene','coding','amino_acid_change','locus'),sep = "__", remove = FALSE)
  res_table$chr = extract_chr(res_table$locus)
  res_table$end = extract_start(res_table$locus)
  res_table$start = extract_start(res_table$locus)
  res_table = dplyr::relocate(res_table, chr, start, end)
  return(res_table)
}
snv_read = function(filepath){
  foi = readr::read_tsv(filepath)
  foi = tidyr::unite(foi, col = 'uid', c(gene,coding,amino_acid_change,locus), remove = FALSE, sep = "__")
  foi$filepath = filepath
  foi = dplyr::relocate(foi, percent_frequency)
  base_name = basename(dirname(unique(foi$filepath)))
  colnames(foi) = gsub("percent_frequency", base_name, colnames(foi))
  return(foi)
}

variant_complete_table = function(snv_path_1, snv_path_2){
  snv_path_1 = as.character(snv_path_1)
  snv_path_2 = as.character(snv_path_2)
  f1 = snv_read(snv_path_1)
  f2 = snv_read(snv_path_2)
  fa1 = dplyr::select(f1, uid, 1) %>% dplyr::distinct()
  fa2 = dplyr::select(f2, uid, 1) %>% dplyr::distinct()
  complete_table = dplyr::full_join(fa1,fa2, by = c("uid"))
  return(complete_table)
}

##### IGV coordinates
report_igv_coords = function(snv_path_1, snv_path_2){
  snv_path_1 = as.character(snv_path_1)
  snv_path_2 = as.character(snv_path_2)
  dir_path_1 = dirname(dirname(snv_path_1))
  dir_path_2 = dirname(dirname(snv_path_2))
  if(dir_path_1 == dir_path_2){
    compl_table = variant_complete_table(snv_path_1, snv_path_2)
    subset_table = variant_subset_table(compl_table)
    igv_coords_path = paste0(dir_path_1, '/igv_coords.txt')
    if(!is.na(subset_table)){
    subset_table = add_coordinates(subset_table)
    subset_table = join_parameters_and_res(subset_table)
    subset_table = dplyr::select(subset_table, -uid)
    readr::write_tsv(subset_table, file = igv_coords_path)
    }else{
          write.table(NA, file = paste0(dir_path_1, "/no_discordant_variants.log"))
    }
  }
}

variant_subset_table = function(complete_table){
  numeric_table = dplyr::select(complete_table, where(is.numeric))
  missing_hits = complete_table$uid[which(is.na(rowMeans(numeric_table)))]
  if(identical(missing_hits, character(0))){
    return(NA)
  }
  subset_table = subset(complete_table, uid %in% missing_hits)
  subset_table = tidyr::pivot_longer(subset_table,-c(uid)) %>%
  dplyr::filter(!is.na(value))
  #subset_table_ls = dplyr::group_by(subset_table, name) %>% dplyr::group_split()
  return(subset_table)
}

```

## Aggregate file comparisons by directory structure
```{r}
#diroi = getwd()
preps = list.files(path = diroi, pattern = "prep_snv.txt", recursive = TRUE, full.names = TRUE)
path_table = data.frame(dirs = NA, snv_txt = preps)
path_table$dirs = dirname(dirname(as.character(path_table$snv_txt)))
path_table_ls = dplyr::group_by(path_table, dirs) %>% dplyr::group_split()
```

```{r, eval=FALSE}
return_discordant_variant_coordinates =  function(snv_path_1,snv_path_2){
  complete_table = variant_complete_table(snv_path_1, snv_path_2)
  subset_table = variant_subset_table(complete_table)
  subset_table = subset_table$subset_table
  if(is.na(subset_table)){
    return(NA)
  }
  subset_table_ls = dplyr::group_by(subset_table, name) %>% dplyr::group_split()
  f1 = snv_read(snv_path_1)
  f2 = snv_read(snv_path_2)
  if(length(subset_table_ls)>1){
    if(is.na(subset_table_ls[[1]])){
      list_1 = NA
    }else{
      list_1 = return_discordant_coordinates(f1, subset_table_ls[[1]])
    }
    if(is.na(subset_table_ls[[2]])){
      list_2 = NA
    }else{
      list_2 = return_discordant_coordinates(f2, subset_table_ls[[2]])  
    }
      return(dplyr::bind_rows(list_1, list_2))
  }else{
     list_1 = return_discordant_coordinates(f1, subset_table_ls[[1]])
     return(list_1)
  }
}
```

## Loop over all entries
```{r}
discordant_list = list()
complete_list = list()
for (i in seq_along(path_table_ls)){
  snv_path_1 = as.character(path_table_ls[[i]]$snv_txt[1])
  snv_path_2 = as.character(path_table_ls[[i]]$snv_txt[2])
  report_igv_coords(snv_path_1, snv_path_2)
  #f_total = dplyr::bind_rows(f1, f2)
  complete_table = variant_complete_table(snv_path_1,snv_path_2)
  subset_table = variant_subset_table(complete_table)
  discordant_list[[i]] = subset_table
  complete_table = tidyr::pivot_longer(complete_table,-c(uid)) 
  complete_list[[i]] = complete_table
}

```

```{r}
complete_tbl = remove_na_entries(complete_list)
discordant_tbl = remove_na_entries(discordant_list)

complete_table = add_coordinates(complete_tbl)
discordant_table = add_coordinates(discordant_tbl)

compl = join_parameters_and_res(complete_table) 
disc = join_parameters_and_res(discordant_table)

```

## Generate Variant/WF counts
```{r}
total_variants_count = count_variant_wf_version(compl)
discordant_variants_count = count_variant_wf_version(disc)
concordant_ls = compl %>%
  dplyr::group_by(pcr_id, uid) %>%
  dplyr::group_split()
concordant_ls = dplyr::bind_rows(concordant_ls[which(unlist(lapply(concordant_ls, nrow)) == 2)])
concordant_variants_count = count_variant_wf_version(concordant_ls)
```

```{r}
# detailed exports
readr::write_tsv(disc, paste0(diroi,"/Discordant_variant_list_filename.tsv"))
readr::write_tsv(concordant_ls, paste0(diroi,"/Concordant_variant_list_filename.tsv"))
readr::write_tsv(compl, paste0(diroi,"/Complete_variant_list_filename.tsv"))

## summary exports 
readr::write_tsv(discordant_variants_count, paste0(diroi,"/Discordant_variant_workflow_count.tsv"))
readr::write_tsv(concordant_variants_count, paste0(diroi,"/Concordant_variant_workflow_count.tsv"))
readr::write_tsv(total_variants_count, paste0(diroi,"/Complete_variant_workflow_count.tsv"))

```

# 
```{r}
group_split_variants = function(variant_table){
  variant_ls = dplyr::group_by(variant_table, uid) %>%
  dplyr::select(-c(chr, start, end, name, locus)) %>%
  dplyr::group_split()
  return(variant_ls)
}

write_out_variants = function(variant_element){
  if(!dir.exists('variants_directory')){
    dir.create('variants_directory')
  }
  filename = unique(variant_element$uid)
  filename = stringr::str_replace(filename, pattern = ':', replacement = "__")
  filename = paste0(diroi,'/variants_directory/', filename, ".tsv")
  readr::write_tsv(variant_element, file = filename)
}

lapply(group_split_variants(disc) , write_out_variants)
group_split_variants(disc)[[1]]$uid

```



## Overviews
### Total variant counts
```{r}
total_variants_count = dplyr::ungroup(total_variants_count)
total_variants_count = dplyr::select(total_variants_count, -c(1:3))
dload_DT(total_variants_count)
```

### Discordant variant counts
```{r}
discordant_variants_count = dplyr::ungroup(discordant_variants_count)
discordant_variants_count = dplyr::select(discordant_variants_count, -c(1:3))
dload_DT(discordant_variants_count)
```

### Concordant variant counts
```{r}
concordant_variants_count = dplyr::ungroup(concordant_variants_count)
concordant_variants_count = dplyr::select(concordant_variants_count, -c(1:3))
dload_DT(concordant_variants_count)
```

